[project]
name = "aaanimal"
classifier = []
maintainer = "Reilly Tucker Siemens"
maintainer-email = "reilly@tuckersiemens.com"
requires-python = ">=3.8"

[build-system]
requires = ["maturin>=0.11,<0.12"]
build-backend = "maturin"
